#@ load("@ytt:data", "data")
#@ load("@ytt:template", "template")
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: #@ data.values.gcp.projectID
  name: infrastructure